### ISSUE TITLE
Additional OSISAF datasets

### ISSUE THREAD

**Issue by kevinmarlis** [ECCO-GROUP/ECCO-pipeline#31]
- https://osi-saf.eumetsat.int/products/osi-450-a (1978-2020)
- https://osi-saf.eumetsat.int/products/osi-430-a (2021-Oct 2023)

Fields of interest: `ice_conc` and `total_standard_uncertainty`

Note: 

> OSI-430-a
> has two data streams: 1) the "nominal" ICDR that applies exactly the same algorithm
> as OSI-450-a and has a latency of 16 days, and 2) the "fast-track" ICDR that applies
> a slightly different algorithm (tie-point selection) and achieves a latency of 2 days.
> The fast-track ICDR was introduced for the third release after requests from
> operational climate users.

**Comment by kevinmarlis** [comment]
As noted in https://github.com/ECCO-GROUP/ECCO-pipeline/issues/43#issuecomment-1771337472, the `401-d` data is available in the same location as before. They also don't appear to have reprocessed the historical data. At some point we lose the `confidence_level` variable in the data, which complicates things.

**Comment by ifenty** [comment]
### datasets

1. [450-a ](ftp://osisaf.met.no/reprocessed/ice/conc/v3p0)(CDR) 1978-2020 [ftp site directory "ice/conc/v3p0"]
1. [430-a](ftp://osisaf.met.no/reprocessed/ice/conc-cont-reproc/v3p0) (CDR) 2021-Oct 2023 (currently) [ftp site directory "conc-cont-reproc/v3p0"]

_430-a seems to be quite up to date (10/2023 as of 10/31/2023)_

### fields
in both 430-a and 450-a the fields of interest are **'ice_conc'** and **"total_standard_uncertainty"** (edited)

**Comment by kevinmarlis** [comment]
We are deprecating 401-d and adding 450-a and 430-a. The top comment is edited
